export enum JabType {
  ALL = "ALL", 
  CORNER_INVITE = "CORNER_INVITE",
  FEEDBACK = "FEEDBACK",
  NEWSLETTER = "NEWSLETTER",
  REMINDERS = "REMINDERS",
  WEEKLY_FIGHTS_UPDATE = "WEEKLY_FIGHTS_UPDATE",
  WELCOME = "WELCOME",
}