
export enum GrantedVia {
  HMAC_INVITE = "HMAC_INVITE",
  CORNER = "CORNER",
}
export enum JabType {
  CORNER_INVITE = "CORNER_INVITE",
  FEEDBACK = "FEEDBACK",
  FIGHT_NIGHT_INVITE = "FIGHT_NIGHT_INVITE",
  NEWSLETTER = "NEWSLETTER",
  REMINDERS = "REMINDERS",
  WEEKLY_FIGHTS_UPDATE = "WEEKLY_FIGHTS_UPDATE",
  WELCOME = "WELCOME",
}