
export enum FeedbackType {
  BUG_REPORT = "BUG_REPORT",
  FEATURE_REQUEST = "FEATURE_REQUEST",
  GENERAL_COMMENT = "GENERAL_COMMENT",
  REQUEST_FIGHT_NIGHT_ACCESS = "REQUEST_FIGHT_NIGHT_ACCESS",
  REQUEST_MORE_FIGHTCOINS = "REQUEST_MORE_FIGHTCOINS",
  OTHER = "OTHER",
}
export enum GrantedVia {
  HMAC_INVITE = "HMAC_INVITE",
  CORNER = "CORNER",
}
export enum JabType {
  CORNER_INVITE = "CORNER_INVITE",
  FEEDBACK = "FEEDBACK",
  FIGHT_NIGHT_INVITE = "FIGHT_NIGHT_INVITE",
  NEWSLETTER = "NEWSLETTER",
  REMINDERS = "REMINDERS",
  WEEKLY_FIGHTS_UPDATE = "WEEKLY_FIGHTS_UPDATE",
  WELCOME = "WELCOME",
}